import type { Metadata } from "next";
import { Geist, Geist_Mono, Madimi_One } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const madimiOne = Madimi_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-madimi-one",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Madimi+One&display=swap"
          rel="stylesheet"
        />
        <Script
          type="module"
          src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"
        />
        {/* <script
          type="module"
          src="https://ajax.googleapis.com/ajax/libs/model-viewer/4.0.0/model-viewer.min.js"
        ></script> */}
        <script src="https://cdn.jsdelivr.net/npm/webxr-polyfill@latest/build/webxr-polyfill.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/webxr-api@latest/dist/webxr-api.js"></script>
      </head>
      <body className={`${madimiOne.variable} antialiased bg-black/20`}>
        {children}
      </body>
    </html>
  );
}
