import type { Metadata } from "next";
import { Geist, Geist_Mono, Madimi_One } from "next/font/google";
import "./globals.css";

const madimiOne = Madimi_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-madimi-one",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Madimi+One&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${madimiOne.variable} antialiased bg-black/20`}>
        {children}
      </body>
    </html>
  );
}
